import React, { createContext, useContext, useEffect, useState } from 'react';

export type AppLanguage = 'sq' | 'en' | 'sr';

const LANGUAGE_STORAGE_KEY = 'bmedical_language';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const translations: any = {
  sq: {
    languageNames: { sq: 'Shqip', en: 'English', sr: 'Srpski' },
    nav: {
      tag: 'PLATFORMA E KLINIKES',
      features: 'Karakteristikat',
      modules: 'Modulet',
      pricing: 'Cmimet',
      customers: 'Klientet',
      contact: 'Kontakti',
      login: 'Hyrje',
      clinicLogin: 'Hyrja e Klinikes / Ordinances',
      ordinanceLogin: 'Hyrja e Klinikes / Ordinances',
      hospitalLogin: 'Hyrja e Spitalit',
      startTrial: 'Fillo proven falas',
      signUp: 'Regjistrohu',
    },
    footer: {
      description: 'Platforma e plote e menaxhimit per klinika fizioterapie, qendra rehabilitimi dhe spitale ne Europe.',
      product: 'Produkti',
      login: 'Hyrje',
      company: 'Kompania',
      legal: 'Ligjore',
      about: 'Rreth nesh',
      careers: 'Karriera',
      partners: 'Partnere',
      terms: 'Kushtet e Sherbimit',
      privacy: 'Privatesia',
      cookies: 'Cookies',
      gdpr: 'GDPR',
      rights: 'Te gjitha te drejtat e rezervuara.',
      compliance: 'Me baze ne BE · Ne perputhje me GDPR',
      uptime: 'SLA 99.9% uptime',
    },
    hero: {
      badge: 'Ne perputhje me GDPR · Siguri e nivelit spitalor',
      titleStart: 'Sistemi i plote i menaxhimit per',
      titleAccent: 'klinika moderne fizioterapie',
      description: 'I besuar nga klinika, praktika private, qendra rehabilitimi dhe spitale ne Europe. Menaxho pacientet, terminet, trajtimet, faturimin dhe raportet nga nje platforme e vetme e sigurt.',
      startTrial: 'Fillo proven falas',
      requestDemo: 'Kerko demo',
      clinics: 'Klinika te perfshira',
      sessions: 'Seanca te menaxhuara',
      uptime: 'Uptime SLA',
      overview: 'Pasqyra e sotme',
      live: 'Aktive',
      appointments: 'Takime',
      waitingRoom: 'Ne pritje',
      revenueToday: 'Te ardhurat sot',
      completed: 'Perfunduar',
      therapy: 'Terapi manuale',
      rehab: 'Rehabilitim post-operativ',
      electrotherapy: 'Elektroterapi',
      inTreatment: 'Ne trajtim',
      waiting: 'Ne pritje',
    },
    features: {
      eyebrow: 'Karakteristikat e platformes',
      title: 'Gjithcka qe i duhet klinikes tende ne nje platforme te vetme te sigurt',
      description: 'E ndertuar per fizioterapiste, mjeke, recepsioniste dhe finance. Cdo modul eshte projektuar per rrjedhen reale te punes ne nje klinike rehabilitimi.',
      items: [
        ['Menaxhimi i pacienteve', 'Profila te plota, histori mjekesore, dokumente, alergji dhe formulara pelqimi.'],
        ['Termine inteligjente', 'Kalendare drag & drop, zbulim konfliktesh, rezervime te perseritura dhe kujtues.'],
        ['Anamneze dhe diagnoza', 'Formulare te strukturuara, diagnoza gati per ICD dhe shabllone te personalizuara.'],
        ['Plane trajtimi', 'Plane te personalizuara, gjurmim seancash, objektiva rehabilitimi dhe shenime progresi.'],
        ['Faturim', 'Fatura gati per TVSH, pagesa parciale, eksport PDF dhe paketa sherbimesh.'],
        ['Raporte dhe analitike', 'Raporte ditore, javore, mujore dhe vjetore me tregues produktiviteti.'],
        ['Kujtues automatike', 'Kujtues me email per termine, ndjekje, pagesa dhe rivleresime.'],
        ['Printim 80mm + A4', 'Mbeshtejtje per printer termik dhe dokumente profesionale A4.'],
        ['GDPR dhe audit logs', 'Izolim tenant-esh, role aksesesh dhe gjurme te plota per veprime kritike.'],
        ['Multi-location', 'Menaxho spitale, dege dhe klinika satelite nga nje platforme e vetme.'],
        ['Radha e pritjes', 'Check-in/check-out live me kohe pritjeje te vleresuar.'],
        ['Gati per gjuhe te shumta', 'E pergatitur per t u shtrire ne tregje te ndryshme europiane.'],
      ],
    },
    modules: {
      eyebrow: 'Pse kjo platforme',
      title: 'E ndertuar per rehabilitim, jo si nje sistem gjenerik',
      description: 'Shumica e software-ve mjekesore e trajtojne fizioterapine si shtese. Ketu cdo ekran, formular dhe proces eshte menduar specifikisht per pune reale ne klinika, praktika private dhe spitale.',
      reasons: [
        ['Izolim multi-tenant', 'Te dhenat e tua nuk prekin kurre nje klinike tjeter. Izolimi zbatohet ne nivel PostgreSQL me RLS.'],
        ['Leje sipas roleve', '6 role te integruara: Pronari, Fizioterapisti, Mjeku, Recepsionisti, Financieri, Asistenti.'],
        ['Miqesore per recepsionin', 'Check-in me nje klik, panel pritjeje dhe radhe live per sportele te ngarkuara.'],
        ['Gati per prodhim', 'Audit logs, backup-e, versionim dhe mjete GDPR per nje klinike reale.'],
      ],
      coreEyebrow: 'Modulet kryesore',
      coreTitle: '17 module te integruara, pa futje te dyfishte te te dhenave',
      cards: [
        ['Pacientet dhe dokumentet', 'Profila te plota, histori mjekesore, dokumente bashkengjitur, etiketa dhe pelqime.'],
        ['Terminet dhe kalendari', 'Pamje ditore/javore/mujore, rezervime te perseritura, dhoma dhe zbulim konfliktesh.'],
        ['Radha live e pritjes', 'Check-in, statuse ne kohe reale dhe kohe pritjeje per recepsionin.'],
        ['Faturimi', 'TVSH, pagesa parciale, printim termik + A4 dhe eksport PDF.'],
        ['Kujtues me email', 'Per termine, ndjekje, pagesa dhe rivleresime.'],
        ['Raporte dhe analitike', 'Te ardhura, mungesa, produktivitet stafi dhe rritje pacientesh.'],
      ],
    },
    spotlight: {
      badge: 'SALLA E PRITJES',
      title: 'Menaxhim live i radhes per recepsione te ngarkuara',
      description: 'Check-in me nje klik, statuse ne kohe reale dhe kohe pritjeje te llogaritura. Recepsioni e di sakte kush eshte i radhes dhe cila dhome eshte e lire.',
      bullets: [
        'Rrjedhe check-in / check-out',
        'Status live: ne pritje, ne trajtim, perfunduar, vonese',
        'Kohe pritjeje e vleresuar per pacient',
        'Kalendari i dites ne krah te radhes live',
      ],
      waitingToday: 'Salla e pritjes · Sot',
      waiting: 'Ne pritje',
      inTreatment: 'Ne trajtim',
      completed: 'Perfunduar',
      rolesTitle: 'Mjete te fuqishme per cdo rol ne kliniken tende',
      cards: [
        ['Raporte dhe analitike', ['Ditore, javore, mujore, vjetore', 'Produktiviteti i terapisteve', 'Te ardhura dhe anulime', 'Intervale datash te personalizuara']],
        ['Faturim', ['Fatura gati per TVSH', 'Pagesa parciale dhe paketa', 'PDF + printim termik 80mm', 'Cash, kartelë, transferte bankare']],
        ['Kujtues me email', ['Kujtues per termine', 'Automatizime follow-up', 'Kujtues pagesash', 'Kujtues rivleresimi']],
      ],
    },
    pricing: {
      eyebrow: 'Cmim i thjeshte dhe transparent',
      title: 'Zgjidh planin qe i pershtatet klinikes ose spitalit tend',
      description: 'Fillo me prove falas 14-ditore. Pa karte krediti. Ndal kur te duash.',
      startTrial: 'Fillo proven falas',
      contactSales: 'Kontakto shitjet',
      mostPopular: 'ME I KERKUARI',
      professionalDesc: 'Per klinika, ordinanca dhe praktika private me nje lokacion',
      enterpriseDesc: 'Per spitale, qendra rehabilitimi dhe klinika me shume lokacione',
      yearly: 'vjetore',
      custom: 'Sipas kerkeses',
      perMonth: '/ muaj',
      professional: [
        'Nje lokacion',
        'Deri ne 3 llogari stafi',
        'Deri ne 30 fatura / muaj',
        'Menaxhim pacientesh',
        'Menaxhim terminesh',
        'Menaxhim i salles se pritjes',
        'Anamneze dhe diagnoza baze',
        'Shabllone diagnozash te kufizuara',
        'Kujtues te kufizuar me email',
        'Raporte baze',
        'Analitike te avancuara',
        'Multi-location / spital',
        'Branding i personalizuar ne PDF',
        'Integrime API',
      ],
      enterprise: [
        'Llogari stafi pa limit',
        'Fatura pa limit',
        'Shabllone diagnozash pa limit',
        'Kujtues dhe automatizime pa limit',
        'Raportim i plote dhe analitike te avancuara',
        'Mbeshtejtje per multi-location dhe spitale',
        'Branding i personalizuar ne PDF dhe dokumente',
        'Raporte financiare te avancuara',
        'Analitike performance per stafin',
        'Mbeshtejtje prioritare 24/7',
        'Mjete te plota eksporti te dhenash',
        'Gati per API / integrime',
        'Paketa te avancuara trajtimi',
        'Menaxher i dedikuar llogarie',
      ],
    },
    testimonials: {
      eyebrow: 'E dashur nga klinikat',
      title: 'E besuar ne Europe',
      items: [
        'Platforma na e ka pergjysmuar ngarkesen ne recepsion. Vetem paneli i salles se pritjes e justifikon abonimin.',
        'Menaxhojme mijera paciente ne disa lokacione nga nje platforme e vetme. Raportet na kane kursyer jave pune manuale.',
        'Cdo rrjedhe klinike ndihet e menduar mire. Anamneza, diagnozat dhe planet e trajtimit duken sikur jane ndertuar nga fizioterapiste per fizioterapiste.',
      ],
    },
    faq: {
      eyebrow: 'Pyetje te shpeshta',
      title: 'Pyetjet me te zakonshme',
      items: [
        ['A jane te izoluara te dhenat e klinikes time?', 'Po. Cdo klinike ose spital ka hapesiren e vet te izoluar. Izolimi zbatohet ne nivel PostgreSQL me tenant_id dhe politika RLS.'],
        ['A mund t i importoj pacientet dhe terminet ekzistuese?', 'Po. Planet Enterprise perfshijne ndihme per migrim, ndersa klientet Professional mund te importojne me CSV.'],
        ['Cfare ndodh pas perfundimit te proves falas?', 'Te dhenat ruhen. Mund te zgjedhesh nje plan, te vazhdosh ose t i eksportosh ne format CSV/PDF.'],
        ['A mbeshtet printere termike?', 'Po. Mbeshtejtim printim termik 80mm si dhe fatura, oferta dhe raporte profesionale A4.'],
        ['A eshte ne perputhje me GDPR?', 'Po. Te dhenat ruhen ne qendra europiane dhe jane te enkriptuara ne tranzit dhe ne pushim.'],
        ['A mund te kaloj me vone nga Professional ne Enterprise?', 'Po, ne cdo kohe dhe pa humbje te dhenash ose downtime.'],
        ['Cilat role mbeshteten brenda nje klinike?', 'Pronari, Fizioterapisti, Mjeku/Specialisti, Recepsionisti, Financieri dhe Asistenti.'],
        ['A ofron API?', 'Po, qasja API eshte e disponueshme ne planet Enterprise.'],
      ],
    },
    contact: {
      eyebrow: 'Rezervo nje demo',
      title: 'Ta ndertojme bashke te ardhmen e klinikes tende',
      description: 'Kerko nje demo te personalizuar dhe ekipi yne do te te tregoje si platforma mund ta thjeshtoje punen tende ne me pak se 30 minuta.',
      successTitle: 'Faleminderit!',
      successBody: 'Kerkesa jote per demo u pranua. Do te kontaktojme brenda 24 oreve.',
      sendAnother: 'Dergo nje tjeter',
      fullName: 'Emri i plote *',
      email: 'Email *',
      clinic: 'Klinika / Spitali',
      phone: 'Telefoni',
      help: 'Si mund te te ndihmojme? *',
      request: 'Kerko demo',
      missingTitle: 'Mungojne fusha',
      missingBody: 'Ploteso emrin, emailin dhe mesazhin.',
      requestTitle: 'Kerkesa u pranua',
      requestBody: 'Ekipi yne do te te kontaktoje brenda 24 oreve.',
    },
    login: {
      back: 'Kthehu ne balline',
      welcome: 'Mire se u ktheve',
      description: 'Hyr ne hapesiren tende te punes',
      username: 'Username',
      signIn: 'Hyr',
      signingIn: 'Duke hyre...',
      clinic: 'Hyrja e Klinikes',
      ordinance: 'Hyrja e Klinikes / Ordinances',
      hospital: 'Hyrja e Spitalit',
      default: 'Hyrje',
      successTitle: 'Mire se erdhe',
      successBody: 'Po ridrejtohesh ne panelin tend...',
      errorTitle: 'Hyrja deshtoi',
    },
    register: {
      back: 'Kthehu ne balline',
      title: 'Fillo proven falas 14-ditore',
      description: 'Krijo hapesiren e klinikes tende per me pak se 2 minuta. Pa karte krediti.',
      bullets: [
        'Hapesire e izoluar per tenant',
        'Menaxhim i plote pacientesh dhe terminesh',
        'Salle pritjeje + faturim + raporte',
        'Ndal kur te duash, pa bllokim',
      ],
      business: 'Emri i biznesit / klinikes / spitalit *',
      owner: 'Emri i plote i pronarit / mjekut / fizioterapistit *',
      email: 'Email *',
      phone: 'Telefoni *',
      password: 'Fjalekalimi *',
      address: 'Adresa *',
      city: 'Qyteti *',
      country: 'Shteti *',
      tax: 'TVSH / NIPT *',
      plan: 'Plani i abonimit *',
      professionalMeta: 'EUR 50 / muaj · prove 14-ditore',
      enterpriseMeta: 'Vjetore · kontakto shitjet',
      agreeStart: 'Pajtohem me ',
      terms: 'Kushtet e Sherbimit',
      privacy: 'Politiken e Privatesise',
      create: 'Krijo hapesiren',
      creating: 'Duke krijuar...',
      haveAccount: 'Ke tashme llogari?',
      signIn: 'Hyr',
      successTitle: 'Mire se erdhe ne Bmedical',
      successBody: 'Hapesira jote u krijua me sukses.',
      errorTitle: 'Regjistrimi deshtoi',
    },
    admin: {
      back: 'Kthehu ne website',
      title: 'Administratori i Platformes',
      badge: 'Qasje e Super Admin · /Adminstaff',
      area: 'Zone e kufizuar',
      username: 'Username',
      password: 'Fjalekalimi',
      signIn: 'Hyr ne platforme',
      signingIn: 'Duke hyre...',
      successTitle: 'Mire se erdhe, admin',
      successBody: 'Po ridrejtohesh ne panelin e platformes...',
      errorTitle: 'Hyrja deshtoi',
    },
    legal: {
      updated: 'Perditesuar me',
      terms: 'Kushtet',
      privacy: 'Privatesia',
      cookies: 'Cookies',
      notFound: 'Nuk u gjet',
      docs: {
        terms: {
          title: 'Kushtet e Sherbimit',
          sections: [
            ['1. Pranimi i kushteve', 'Duke perdorur platformen, pajtoheni me keto Kushte te Sherbimit. Sherbimi operohet nga Bmedical.'],
            ['2. Abonimi dhe faturimi', 'Sherbimi ofrohet me abonim. Plani Professional faturohet €50 ne muaj, ndersa Enterprise me cmim te personalizuar sipas procesit te onboardimit.'],
            ['3. Prova falas', 'Klientet e rinj perfitojne prove falas 14-ditore. Nuk kerkohet karte krediti.'],
            ['4. Te dhenat e tenant-it', 'Te dhenat qe ngarkoni mbeten prona juaj. Platforma vepron si perpunues i te dhenave sipas GDPR.'],
            ['5. Perdorimi i lejueshem', 'Nuk lejohet keqperdorimi i sherbimit, shkelja e sigurise apo ruajtja e permbajtjes se paligjshme.'],
            ['6. Kufizimi i pergjegjesise', 'Bmedical nuk mban pergjegjesi per deme indirekte apo pasoja nga perdorimi i sherbimit.'],
            ['7. Nderprerja', 'Mund ta anuloni abonimin ne cdo kohe. Pas nderprerjes, keni 30 dite kohe per eksport te te dhenave.'],
          ],
        },
        privacy: {
          title: 'Politika e Privatesise',
          sections: [
            ['1. Kontrolluesi i te dhenave', 'Bmedical eshte kontrolluesi i te dhenave per informacionin e llogarise dhe faturimit.'],
            ['2. Te dhenat qe mbledhim', 'Informacion llogarie, te dhena faturimi, komunikime me support dhe analiza perdorimi.'],
            ['3. Pajtueshmeria me GDPR', 'Jemi ne perputhje me GDPR dhe ruajme te dhenat ne qendra te dhenash brenda BE-se.'],
            ['4. Siguria e te dhenave', 'Te gjitha te dhenat enkriptohen ne tranzit dhe ne pushim. Izolimi i tenant-eve zbatohet ne PostgreSQL.'],
            ['5. Te drejtat tuaja', 'Keni te drejte per qasje, korrigjim, fshirje dhe eksport te te dhenave tuaja.'],
            ['6. Ruajtja e te dhenave', 'Te dhenat e llogarise ruhen gjate abonimit plus 30 dite. Backup-et ruhen 90 dite.'],
            ['7. Kontakti', 'Data Protection Officer: dpo@bmedical.health'],
          ],
        },
        cookies: {
          title: 'Politika e Cookies',
          sections: [
            ['1. Cfare jane cookies?', 'Cookies jane skedare te vegjel teksti qe ruhen ne pajisjen tuaj.'],
            ['2. Cookies esenciale', 'Perdorim cookies te domosdoshme per autentikim, menaxhim sesioni dhe siguri.'],
            ['3. Cookies analitike', 'Me pelqimin tuaj mund te perdorim analiza privacy-friendly per te kuptuar perdorimin e produktit.'],
            ['4. Cookies marketingu', 'Faqja marketing mund te perdore cookies per atribim vizitoresh vetem pas pelqimit.'],
            ['5. Menaxhimi i cookies', 'Preferencat e cookies mund t i menaxhoni nga shfletuesi ose nga banner-i i cookies.'],
          ],
        },
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  en: {} as any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  sr: {} as any,
};

translations.en = {
  languageNames: { sq: 'Shqip', en: 'English', sr: 'Srpski' },
  nav: {
    tag: 'CLINIC PLATFORM',
    features: 'Features',
    modules: 'Modules',
    pricing: 'Pricing',
    customers: 'Customers',
    contact: 'Contact',
    login: 'Login',
    clinicLogin: 'Clinic / Ordinance Login',
    ordinanceLogin: 'Clinic / Ordinance Login',
    hospitalLogin: 'Hospital Login',
    startTrial: 'Start Free Trial',
    signUp: 'Sign Up',
  },
  footer: {
    description: 'The complete practice management platform for physiotherapy clinics, rehabilitation centers and hospitals across Europe.',
    product: 'Product',
    login: 'Login',
    company: 'Company',
    legal: 'Legal',
    about: 'About',
    careers: 'Careers',
    partners: 'Partners',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    cookies: 'Cookie Policy',
    gdpr: 'GDPR',
    rights: 'All rights reserved.',
    compliance: 'EU-based · GDPR compliant',
    uptime: '99.9% uptime SLA',
  },
  hero: {
    badge: 'GDPR Compliant · Hospital-Grade Security',
    titleStart: 'The Complete Practice Management System for',
    titleAccent: 'Modern Physiotherapy Clinics',
      description: 'Trusted by clinics, private practices, rehabilitation centers and hospitals across Europe. Manage patients, appointments, treatments, billing and reports from a single secure platform.',
    startTrial: 'Start Free Trial',
    requestDemo: 'Request a Demo',
    clinics: 'Clinics onboarded',
    sessions: 'Sessions managed',
    uptime: 'Uptime SLA',
    overview: "Today's Overview",
    live: 'Live',
    appointments: 'Appointments',
    waitingRoom: 'In Waiting Room',
    revenueToday: 'Revenue Today',
    completed: 'Completed',
    therapy: 'Manual Therapy',
    rehab: 'Post-op Rehab',
    electrotherapy: 'Electrotherapy',
    inTreatment: 'In Treatment',
    waiting: 'Waiting',
  },
  features: {
    eyebrow: 'Platform Features',
    title: 'Everything your clinic needs in one secure platform',
    description: 'Built for physiotherapists, doctors, receptionists and finance teams. Every module is designed for real rehabilitation workflows.',
    items: [
      ['Patient Management', 'Full patient profiles, medical history, documents, allergies and consent forms.'],
      ['Smart Appointments', 'Drag-and-drop calendar, conflict detection, recurring bookings and reminders.'],
      ['Anamnesis & Diagnoses', 'Structured intake forms, ICD-ready diagnoses and custom templates.'],
      ['Treatment Plans', 'Personalized plans, session tracking, rehab milestones and progress notes.'],
      ['Billing & Invoicing', 'VAT-ready invoices, partial payments, PDF export and package billing.'],
      ['Reports & Analytics', 'Daily, weekly, monthly and yearly reports with productivity insights.'],
      ['Automated Reminders', 'Email reminders for appointments, follow-ups, payments and re-evaluations.'],
      ['80mm + A4 Printing', 'Support for thermal printers and professional A4 documents.'],
      ['GDPR & Audit Logs', 'Tenant isolation, role-based access and a full audit trail for critical actions.'],
      ['Multi-location', 'Manage hospitals, branches and satellite clinics from one platform.'],
      ['Waiting Room Queue', 'Live check-in/check-out workflow with estimated waiting times.'],
      ['Language-ready', 'Prepared to scale across multiple European markets.'],
    ],
  },
  modules: {
    eyebrow: 'Why Bmedical',
    title: 'Purpose-built for rehabilitation, not a generic EHR',
    description: 'Most medical software treats physiotherapy as an afterthought. Every screen, form and workflow here is designed for real rehabilitation teams.',
    reasons: [
      ['Multi-tenant isolation', 'Your data never touches another clinic. Isolation is enforced at the PostgreSQL level with row-level security.'],
      ['Role-based permissions', '6 built-in roles: Owner, Physiotherapist, Doctor, Receptionist, Accountant, Assistant.'],
      ['Reception-friendly', 'One-click check-in, waiting-room board and live queue for busy front desks.'],
      ['Production-ready', 'Audit logs, backups, versioning and GDPR tools for real-world clinics.'],
    ],
    coreEyebrow: 'Core Modules',
    coreTitle: '17 integrated modules, zero duplicate data entry',
    cards: [
      ['Patients & Documents', 'Complete profiles, medical history, attachments, tags and consent tracking.'],
      ['Appointments & Calendar', 'Day/week/month views, recurring bookings, room assignment and conflict detection.'],
      ['Waiting Room Live Queue', 'Check-in board, real-time statuses and estimated wait times for reception.'],
      ['Invoicing & Billing', 'VAT, partial payments, thermal + A4 printing and PDF export.'],
      ['Email Reminders', 'For appointments, follow-ups, payments and re-evaluations.'],
      ['Reports & Analytics', 'Revenue, no-shows, staff productivity and patient growth.'],
    ],
  },
  spotlight: {
    badge: 'WAITING ROOM',
    title: 'Live queue management built for busy reception desks',
    description: 'One-click check-in, real-time status updates and estimated waiting times. Your front desk always knows who is next and which room is available.',
    bullets: [
      'Check-in / check-out workflow',
      'Real-time status: waiting, in treatment, completed, delayed',
      'Estimated waiting time per patient',
      'Full day calendar alongside live queue',
    ],
    waitingToday: 'Waiting room · Today',
    waiting: 'Waiting',
    inTreatment: 'In treatment',
    completed: 'Completed',
    rolesTitle: 'Powerful tools for every role in your clinic',
    cards: [
      ['Reports & Analytics', ['Daily, weekly, monthly, yearly', 'Therapist productivity', 'Revenue & cancellations', 'Custom date ranges']],
      ['Billing & Invoicing', ['VAT-ready invoices', 'Partial & package payments', 'PDF + 80mm thermal print', 'Cash, card, bank transfer']],
      ['Email Reminders', ['Appointment reminders', 'Follow-up automations', 'Payment reminders', 'Re-evaluation reminders']],
    ],
  },
  pricing: {
    eyebrow: 'Simple, Transparent Pricing',
    title: 'Choose the plan that fits your clinic or hospital',
    description: 'Start with a 14-day free trial. No credit card required. Cancel anytime.',
    startTrial: 'Start Free Trial',
    contactSales: 'Contact Sales',
    mostPopular: 'MOST POPULAR',
    professionalDesc: 'For single-location clinics, ordinances and private practices',
    enterpriseDesc: 'For hospitals, rehab centers and multi-location clinics',
    yearly: 'yearly',
    custom: 'Custom',
    perMonth: '/ month',
    professional: [
      'Single location','Up to 3 staff accounts','Up to 30 invoices / month','Patient management','Appointment scheduling','Waiting room management','Basic anamnesis & diagnoses','Limited diagnosis templates','Limited email reminders','Basic reports','Advanced analytics','Multi-location / hospital','Custom branding on PDFs','API integrations',
    ],
    enterprise: [
      'Unlimited staff accounts','Unlimited invoices','Unlimited diagnosis templates','Unlimited reminders & automations','Full reporting & advanced analytics','Multi-location & hospital support','Custom branding on PDFs & documents','Advanced financial reports','Staff performance analytics','Priority 24/7 support','Full data export tools','API / integration-ready','Advanced treatment packages','Dedicated account manager',
    ],
  },
  testimonials: {
    eyebrow: 'Loved by clinics',
    title: 'Trusted across Europe',
    items: [
      'Bmedical cut our reception workload in half. The waiting-room board alone is worth the subscription.',
      'We manage thousands of patients across multiple locations on a single platform. Reports alone save us weeks of manual work.',
      'Every clinical workflow feels thought through. Structured anamnesis, diagnoses and treatment plans feel built by physios for physios.',
    ],
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'Frequently asked questions',
    items: [
      ['Is my clinic data isolated from other tenants?', 'Yes. Every clinic or hospital gets an isolated workspace. Data isolation is enforced at the PostgreSQL level with tenant_id and row-level security policies.'],
      ['Can I import my existing patients and appointments?', 'Yes. Enterprise plans include migration support, while Professional customers can import through CSV.'],
      ['What happens after my free trial ends?', 'Your data remains preserved. You can choose a plan and continue or export your data in CSV/PDF format at any time.'],
      ['Do you support thermal printers?', 'Yes. We support 80mm thermal receipt printing as well as A4 invoices, offers and reports.'],
      ['Is the platform GDPR compliant?', 'Yes. Data is stored in EU-based data centers and encrypted in transit and at rest.'],
      ['Can I upgrade from Professional to Enterprise later?', 'Absolutely. You can upgrade at any time without downtime or data loss.'],
      ['What roles are supported inside a clinic?', 'Owner, Physiotherapist, Doctor/Specialist, Receptionist, Accountant and Assistant.'],
      ['Do you offer an API?', 'Yes. API access is available on Enterprise plans.'],
    ],
  },
  contact: {
    eyebrow: 'Book a demo',
    title: "Let's build the future of your clinic together",
    description: 'Request a personalized demo and our team will show you how the platform can streamline your work in under 30 minutes.',
    successTitle: 'Thank you!',
    successBody: "Your demo request has been received. We'll be in touch within 24 hours.",
    sendAnother: 'Send another',
    fullName: 'Full name *',
    email: 'Email *',
    clinic: 'Clinic / Hospital',
    phone: 'Phone',
    help: 'How can we help? *',
    request: 'Request demo',
    missingTitle: 'Missing fields',
    missingBody: 'Please fill in name, email and message.',
    requestTitle: 'Request received',
    requestBody: 'Our team will contact you within 24 hours.',
  },
  login: {
    back: 'Back to home',
    welcome: 'Welcome back',
    description: 'Sign in to your workspace',
    username: 'Username',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    clinic: 'Clinic Login',
    ordinance: 'Clinic / Ordinance Login',
    hospital: 'Hospital Login',
    default: 'Sign in',
    successTitle: 'Welcome back',
    successBody: 'Redirecting to your dashboard...',
    errorTitle: 'Login failed',
  },
  register: {
    back: 'Back to home',
    title: 'Start your 14-day free trial',
    description: 'Create your clinic or hospital workspace in under 2 minutes. No credit card required.',
    bullets: ['Isolated tenant workspace', 'Full patient & appointment management', 'Waiting room + billing + reports', 'Cancel anytime, no lock-in'],
    business: 'Business / Clinic / Hospital name *',
    owner: 'Owner / Doctor / Physiotherapist full name *',
    email: 'Email *',
    phone: 'Phone *',
    password: 'Password *',
    address: 'Address *',
    city: 'City *',
    country: 'Country *',
    tax: 'VAT / Tax number *',
    plan: 'Subscription plan *',
    professionalMeta: 'EUR 50 / month · 14-day trial',
    enterpriseMeta: 'Yearly · contact sales',
    agreeStart: 'I agree to the ',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    create: 'Create workspace',
    creating: 'Creating workspace...',
    haveAccount: 'Already have an account?',
    signIn: 'Sign in',
    successTitle: 'Welcome to Bmedical',
    successBody: 'Your workspace has been created.',
    errorTitle: 'Registration failed',
  },
  admin: {
    back: 'Back to website',
    title: 'Platform Admin',
    badge: 'Super Admin Access · /Adminstaff',
    area: 'Restricted area',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign in to platform',
    signingIn: 'Signing in...',
    successTitle: 'Welcome, admin',
    successBody: 'Redirecting to platform dashboard...',
    errorTitle: 'Login failed',
  },
  legal: {
    updated: 'Last updated',
    terms: 'Terms',
    privacy: 'Privacy',
    cookies: 'Cookies',
    notFound: 'Not found',
    docs: {
      terms: {
        title: 'Terms of Service',
        sections: [
          ['1. Acceptance of Terms', 'By using the platform, you agree to these Terms of Service. The service is operated by Bmedical.'],
          ['2. Subscription & Billing', 'The service is provided on a subscription basis. The Professional plan is billed at €50 per month, while Enterprise is custom-priced during onboarding.'],
          ['3. Free Trial', 'New customers receive a 14-day free trial and no credit card is required.'],
          ['4. Tenant Data', 'All tenant data remains your property. The platform acts as a data processor under GDPR.'],
          ['5. Acceptable Use', 'You may not misuse the service, attempt to breach security or store unlawful content.'],
          ['6. Limitation of Liability', 'Bmedical is not liable for indirect or consequential damages arising from the use of the service.'],
          ['7. Termination', 'You may cancel your subscription at any time. After termination, you have 30 days to export your data.'],
        ],
      },
      privacy: {
        title: 'Privacy Policy',
        sections: [
          ['1. Data Controller', 'Bmedical is the data controller for account and billing information.'],
          ['2. Data We Collect', 'We collect account information, billing data, support communications and product usage analytics.'],
          ['3. GDPR Compliance', 'We comply with GDPR and store data in EU-based data centers.'],
          ['4. Data Security', 'All data is encrypted in transit and at rest. Tenant isolation is enforced at the PostgreSQL level.'],
          ['5. Your Rights', 'You have the right to access, rectify, erase and export your data.'],
          ['6. Data Retention', 'Account data is retained for the duration of the subscription plus 30 days. Backups are retained for 90 days.'],
          ['7. Contact', 'Data Protection Officer: dpo@bmedical.health'],
        ],
      },
      cookies: {
        title: 'Cookie Policy',
        sections: [
          ['1. What are cookies?', 'Cookies are small text files stored on your device.'],
          ['2. Essential cookies', 'We use essential cookies for authentication, session management and security.'],
          ['3. Analytics cookies', 'With your consent, privacy-friendly analytics may be used to understand product usage.'],
          ['4. Marketing cookies', 'Marketing cookies are activated only after explicit consent.'],
          ['5. Managing cookies', 'Cookie preferences can be managed in your browser or from the cookie banner.'],
        ],
      },
    },
  },
};

translations.sr = {
  languageNames: { sq: 'Shqip', en: 'English', sr: 'Srpski' },
  nav: {
    tag: 'PLATFORMA KLINIKE',
    features: 'Funkcije',
    modules: 'Moduli',
    pricing: 'Cene',
    customers: 'Klijenti',
    contact: 'Kontakt',
    login: 'Prijava',
    clinicLogin: 'Prijava klinike / ordinacije',
    ordinanceLogin: 'Prijava klinike / ordinacije',
    hospitalLogin: 'Prijava bolnice',
    startTrial: 'Pokreni besplatnu probu',
    signUp: 'Registracija',
  },
  footer: {
    description: 'Kompletna platforma za upravljanje fizioterapijskim klinikama, rehabilitacionim centrima i bolnicama sirom Evrope.',
    product: 'Proizvod',
    login: 'Prijava',
    company: 'Kompanija',
    legal: 'Pravno',
    about: 'O nama',
    careers: 'Karijera',
    partners: 'Partneri',
    terms: 'Uslovi koriscenja',
    privacy: 'Politika privatnosti',
    cookies: 'Politika kolacica',
    gdpr: 'GDPR',
    rights: 'Sva prava zadrzana.',
    compliance: 'EU baza · GDPR usaglaseno',
    uptime: '99.9% uptime SLA',
  },
  hero: {
    badge: 'GDPR usaglaseno · Bezbednost na nivou bolnice',
    titleStart: 'Kompletan sistem upravljanja za',
    titleAccent: 'moderne fizioterapijske klinike',
    description: 'Platformi veruju klinike, ordinacije, rehabilitacioni centri i bolnice sirom Evrope. Upravljajte pacijentima, terminima, tretmanima, naplatom i izvestajima sa jedne sigurne platforme.',
    startTrial: 'Pokreni besplatnu probu',
    requestDemo: 'Zatrazi demo',
    clinics: 'Ukljucenih klinika',
    sessions: 'Vodjenih sesija',
    uptime: 'Uptime SLA',
    overview: 'Danasnji pregled',
    live: 'Uzivo',
    appointments: 'Termini',
    waitingRoom: 'U cekaonici',
    revenueToday: 'Prihod danas',
    completed: 'Zavrseno',
    therapy: 'Manualna terapija',
    rehab: 'Post-operativna rehabilitacija',
    electrotherapy: 'Elektroterapija',
    inTreatment: 'Na tretmanu',
    waiting: 'Ceka',
  },
  features: {
    eyebrow: 'Funkcije platforme',
    title: 'Sve sto je vasoj klinici potrebno na jednoj sigurnoj platformi',
    description: 'Napravljeno za fizioterapeute, lekare, recepcionare i finansije. Svaki modul prati stvarne rehabilitacione tokove rada.',
    items: [
      ['Upravljanje pacijentima', 'Kompletni profili pacijenata, medicinska istorija, dokumenti, alergije i saglasnosti.'],
      ['Pametni termini', 'Drag-and-drop kalendar, otkrivanje konflikata, ponavljanja i podsetnici.'],
      ['Anamneza i dijagnoze', 'Strukturirani formulari, ICD spremne dijagnoze i prilagodjeni sabloni.'],
      ['Planovi tretmana', 'Personalizovani planovi, pracenje sesija i napomena o napretku.'],
      ['Naplata i fakturisanje', 'Fakture spremne za PDV, parcijalna placanja, PDF izvoz i paketi usluga.'],
      ['Izvestaji i analitika', 'Dnevni, nedeljni, mesecni i godisnji izvestaji sa uvidom u produktivnost.'],
      ['Automatski podsetnici', 'Email podsetnici za termine, kontrole, placanja i reevaluacije.'],
      ['80mm + A4 stampa', 'Podrska za termalne stampace i profesionalne A4 dokumente.'],
      ['GDPR i audit logovi', 'Izolacija tenant-a, pristup po rolama i kompletan trag aktivnosti.'],
      ['Vise lokacija', 'Upravljajte bolnicama, ograncima i satelitskim klinikama sa jedne platforme.'],
      ['Red u cekaonici', 'Prijava/odjava uzivo sa procenjenim vremenom cekanja.'],
      ['Spremno za vise jezika', 'Pripremljeno za sirenje na razlicita evropska trzista.'],
    ],
  },
  modules: translations.en.modules,
  spotlight: {
    badge: 'CEKAONICA',
    title: 'Upravljanje redom uzivo za zauzete recepcije',
    description: 'Jednim klikom prijava, statusi u realnom vremenu i procena cekanja. Recepcija uvek zna ko je sledeci i koja soba je slobodna.',
    bullets: [
      'Tok prijave / odjave',
      'Status uzivo: ceka, na tretmanu, zavrseno, kasni',
      'Procena vremena cekanja po pacijentu',
      'Dnevni kalendar uz aktivnu cekaoicu',
    ],
    waitingToday: 'Cekaonica · Danas',
    waiting: 'Ceka',
    inTreatment: 'Na tretmanu',
    completed: 'Zavrseno',
    rolesTitle: 'Mocni alati za svaku ulogu u vasoj klinici',
    cards: [
      ['Izvestaji i analitika', ['Dnevno, nedeljno, mesecno, godisnje', 'Produktivnost terapeuta', 'Prihod i otkazivanja', 'Prilagodljivi datumski opsezi']],
      ['Naplate i fakture', ['Fakture spremne za PDV', 'Delimicna i paketna placanja', 'PDF + 80mm termalna stampa', 'Gotovina, kartica, bankovni transfer']],
      ['Email podsetnici', ['Podsetnici za termine', 'Follow-up automatizacije', 'Podsetnici za placanje', 'Podsetnici za reevaluaciju']],
    ],
  },
  pricing: translations.en.pricing,
  testimonials: {
    eyebrow: 'Klinike nas vole',
    title: 'Platformi se veruje sirom Evrope',
    items: [
      'Platforma nam je prepolovila opterecenje recepcije. Sam panel cekaonice vredi pretplatu.',
      'Upravljamo hiljadama pacijenata na vise lokacija sa jedne platforme. Izvestaji stede nedelje rucnog rada.',
      'Svaki klinicki tok deluje promisljen. Anamneza, dijagnoze i planovi tretmana deluju kao da su ih gradili fizioterapeuti.',
    ],
  },
  faq: translations.en.faq,
  contact: {
    eyebrow: 'Zakazite demo',
    title: 'Hajde da zajedno izgradimo buducnost vase klinike',
    description: 'Zatrazi personalizovani demo i nas tim ce vam pokazati kako platforma moze da ubrza vas rad za manje od 30 minuta.',
    successTitle: 'Hvala!',
    successBody: 'Vas zahtev za demo je primljen. Javicemo vam se u roku od 24 sata.',
    sendAnother: 'Posalji jos jedan',
    fullName: 'Puno ime *',
    email: 'Email *',
    clinic: 'Klinika / Bolnica',
    phone: 'Telefon',
    help: 'Kako mozemo pomoci? *',
    request: 'Zatrazi demo',
    missingTitle: 'Nedostaju polja',
    missingBody: 'Popunite ime, email i poruku.',
    requestTitle: 'Zahtev primljen',
    requestBody: 'Nas tim ce vas kontaktirati u roku od 24 sata.',
  },
  login: {
    back: 'Nazad na pocetnu',
    welcome: 'Dobrodosli nazad',
    description: 'Prijavite se u svoj radni prostor',
    username: 'Username',
    signIn: 'Prijavi se',
    signingIn: 'Prijavljivanje...',
    clinic: 'Prijava klinike',
    ordinance: 'Prijava klinike / ordinacije',
    hospital: 'Prijava bolnice',
    default: 'Prijava',
    successTitle: 'Dobrodosli nazad',
    successBody: 'Preusmeravanje na dashboard...',
    errorTitle: 'Prijava neuspesna',
  },
  register: {
    back: 'Nazad na pocetnu',
    title: 'Pokrenite besplatnu probu od 14 dana',
    description: 'Kreirajte radni prostor klinike za manje od 2 minuta. Kreditna kartica nije potrebna.',
    bullets: ['Izolovan tenant workspace', 'Kompletno upravljanje pacijentima i terminima', 'Cekaonica + naplata + izvestaji', 'Otkazite bilo kada, bez zakljucavanja'],
    business: 'Naziv biznisa / klinike / bolnice *',
    owner: 'Puno ime vlasnika / doktora / fizioterapeuta *',
    email: 'Email *',
    phone: 'Telefon *',
    password: 'Lozinka *',
    address: 'Adresa *',
    city: 'Grad *',
    country: 'Drzava *',
    tax: 'PIB / Poreski broj *',
    plan: 'Pretplatni plan *',
    professionalMeta: '€50 / mesec · 14 dana probe',
    enterpriseMeta: 'Godisnje · kontaktiraj prodaju',
    agreeStart: 'Saglasan sam sa ',
    terms: 'Uslovima koriscenja',
    privacy: 'Politikom privatnosti',
    create: 'Kreiraj workspace',
    creating: 'Kreiranje...',
    haveAccount: 'Vec imate nalog?',
    signIn: 'Prijavite se',
    successTitle: 'Dobrodosli u Bmedical',
    successBody: 'Vas workspace je kreiran.',
    errorTitle: 'Registracija neuspesna',
  },
  admin: {
    back: 'Nazad na sajt',
    title: 'Administrator platforme',
    badge: 'Super Admin pristup · /Adminstaff',
    area: 'Ogranicena zona',
    username: 'Username',
    password: 'Lozinka',
    signIn: 'Prijavi se na platformu',
    signingIn: 'Prijavljivanje...',
    successTitle: 'Dobrodosli, admin',
    successBody: 'Preusmeravanje na dashboard platforme...',
    errorTitle: 'Prijava neuspesna',
  },
  legal: translations.en.legal,
};

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (typeof translations)['sq'];
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<AppLanguage>('sq');

  useEffect(() => {
    try {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as AppLanguage | null;
      if (stored === 'sq' || stored === 'en' || stored === 'sr') {
        setLanguage(stored);
      }
    } catch {
      // Ignore localStorage failures; default language stays active.
    }
  }, []);

  const updateLanguage = (next: AppLanguage) => {
    setLanguage(next);
    try { localStorage.setItem(LANGUAGE_STORAGE_KEY, next); } catch {
      // Ignore localStorage failures; in-memory language still updates.
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t: translations[language] as (typeof translations)['sq'] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
